services:
  db:
    image: mysql:8.0
    container_name: ${DB_CONTAINER_NAME:-catty-db}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-catty_reminders}
      MYSQL_USER: ${MYSQL_USER:-catty}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-cattypass}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - catty-network

  catty-app:
    image: ${IMAGE:-ghcr.io/kuzminstanislav/catty-reminders-app:latest}
    container_name: ${APP_CONTAINER_NAME:-catty-app}
    restart: always
    environment:
      DEPLOY_REF: ${DEPLOY_REF:-latest}
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: ${MYSQL_USER:-catty}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-cattypass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-catty_reminders}
    ports:
      - "${HOST_APP_PORT:-8181}:${CONTEINER_APP_PORT:-8181}"
    volumes:
      - ./config.json:/app/config.json:ro
      - ./reminder_db.json:/app/reminder_db.json
    depends_on:
      - db
    networks:
      - catty-network

networks:
  catty-network:
    driver: bridge

volumes:
  db_data:
