services:
  db:
    image: mysql:8.0
    container_name: catty-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - catty-network

  catty-app:
    image: ${IMAGE}
    container_name: ${APP_CONTAINER_NAME}
    restart: always
    environment:
      DEPLOY_REF: ${DEPLOY_REF}
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${HOST_APP_PORT}:${CONTEINER_APP_PORT}"
    volumes:
      - ./config.json:/app/config.json:ro
      - ./reminder_db.json:/app/reminder_db.json
    depends_on:
      - db
    networks:
      - catty-network

networks:
  catty-network:
    driver: bridge

volumes:
  db_data:
