name: CD

on:
  release:
    types: [published]
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: course.prafdin.space
          port: 3149
          username: vboxuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 30m
          script: |
            set -e
            cd /home/vboxuser/catty-reminders-app

            TARGET_SHA="${{ github.event.workflow_run.head_sha || github.sha }}"

            export DEPLOY_REF="$TARGET_SHA"
            export IMAGE="ghcr.io/kuzminstanislav/catty-reminders-app:$TARGET_SHA"

            echo "IMAGE=$IMAGE" > .env
            echo "DEPLOY_REF=$DEPLOY_REF" >> .env

            echo "${{ secrets.GITHUB_TOKEN }}" | sudo docker login ghcr.io -u kuzminstanislav --password-stdin

            sudo -E docker compose up -d --pull always --remove-orphans --force-recreate
